name: 🌆 Issue with municipality
description: A problem with or improvement for an existing CivicBand site
labels: ["site-issue"]
type: Bug

body:
  - type: markdown
    attributes:
      Thank you for taking the time to submit an issue with an existing 
      CivicBand site!

      Please title your issue with the name of the municipality, followed by a
      brief bug desccription.

  - type: input
    id: subdomain
    attributes:
      label: Subdomain
      description: Subdomain is everything before the .civic.band in the url.

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide a description of the issue.
      value: |
        <!-- A clear and concise description of the problem behavior, including what is happening, and what you expected to happen. -->
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist for new issues
      options:
        - label: I will abide by the CivicBand [Code of Conduct](https://github.com/civicband/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I have searched the existing issues and believe this is not a duplicate
          required: true